import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { ToggleProvider } from "@/context/ToggleSideBarContext";
import Topbar from "@/components/Topbar";
import ResponsiveMenu from "@/components/ResponsiveMenu";
import Player from "@/components/Player";
import { SongProvider } from "@/context/SongContext";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <SongProvider>
        <ToggleProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black `}
          >
            
            <Sidebar />
            <Topbar />
            <ResponsiveMenu />
            <Player />
            {children}

          </body>
        </ToggleProvider>
      </SongProvider>
    </html>
  );
}
